core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="ToDo API",
        default_version="v1",
        description="This is API documentation for ToDo project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mimisaif@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("todo.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

core/todo/api/v1/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views

app_name = "api-v1"

router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")


urlpatterns = [
    path("", include(router.urls)),
    path("weather/<str:city_name>", views.WeatherApiView.as_view(), name="weather"),
]

core/todo/urls.py
from django.urls import path, include
from .views import (
    TaskListView,
    TaskCreateView,
    TaskDoneView,
    TaskEditView,
    TaskDeleteView,
)

app_name = "todo"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("done/<int:pk>/", TaskDoneView.as_view(), name="task-done"),
    path("edit/<int:pk>/", TaskEditView.as_view(), name="task-edit"),
    path("delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models

# Create your models here.


class Task(models.Model):

    user = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    done = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

core/todo/forms.py
from django import forms
from .models import Task


class TaskEditForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
            }
        ),
        label="",
    )

    class Meta:
        model = Task
        fields = ["title"]

core/todo/api/v1/views.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
import requests
from .serializers import TodoSerializer
from .permissions import IsOwnerOrReadOnly
from ...models import Task


class TaskModelViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["done"]


class WeatherApiView(APIView):
    @method_decorator(cache_page(20 * 60))
    def get(self, request, *args, **kwargs):
        city_name = kwargs.get("city_name")
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid=e1176c2224faec7d17373814500b2fa7"
        response = requests.get(url)
        return JsonResponse(response.json())

core/todo/views.py
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.core.cache import cache
import requests
from accounts.models import Profile
from .models import Task
from .forms import TaskEditForm


class TaskBaseView:
    model = Task

    def get_weather_data(self):
        city_name = "mashhad"
        api_key = "e1176c2224faec7d17373814500b2fa7"
        cache_key = f"weather_data_{city_name}"
        weather_data = cache.get(cache_key)

        if not weather_data:
            url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"
            try:
                response = requests.get(url)
                response.raise_for_status()
                weather_data = response.json()
                if "main" in weather_data and "temp" in weather_data["main"]:
                    weather_data["main"]["temp_celsius"] = int(
                        weather_data["main"]["temp"] - 273.15
                    )
                # Cache the weather data for 20 minutes
                cache.set(cache_key, weather_data, 20 * 60)
            except requests.RequestException:
                weather_data = {"error": "Unable to fetch weather data"}

        return weather_data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["weather"] = self.get_weather_data()
        return context


class TaskListView(LoginRequiredMixin, TaskBaseView, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/task_list.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user.id)


class TaskCreateView(LoginRequiredMixin, TaskBaseView, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:task-list")

    def form_valid(self, form):
        form.instance.user = Profile.objects.get(user=self.request.user)
        return super(TaskCreateView, self).form_valid(form)


class TaskEditView(LoginRequiredMixin, TaskBaseView, UpdateView):
    model = Task
    form_class = TaskEditForm
    template_name = "todo/edit_task.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(LoginRequiredMixin, TaskBaseView, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:task-list")


class TaskDoneView(LoginRequiredMixin, TaskBaseView, ListView):
    model = Task
    success_url = reverse_lazy("todo:task-list")

    def get(self, request, *args, **kwargs):
        task = Task.objects.get(pk=kwargs.get("pk"))
        task.done = True
        task.save()
        return redirect(self.success_url)

core/templates/todo/edit_task.html
{% extends "base.html"%}

{% block content %}
<form method="post" action="{% url 'todo:task-edit' pk=task.id %}">
    {% csrf_token %}
    {{form}}
    <div>
        <button type="submit" class="btn btn-primary btn-edit">Edit</button>
    </div>
</form>

</div>
</div>
</div>
</div>
{% endblock %}

core/templates/todo/task_confirm_delete.html
{% extends "base.html"%}

{% block content %}
                                        <form method="post" action="{% url 'todo:task-delete' pk=task.id %}">
                                            {% csrf_token %}
                                            <p class="delete-page">Are you sure you want to delete "{{ task }}"?</p>
                                            <div>
                                                <button type="submit" class="btn btn-primary btn-edit" value="content">Delete</button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endblock %}
<form method="post">{% csrf_token %}
     
 
 
 
    <p>Are you sure you want to delete "{{ task }}"?</p>
     
     
     
     
        <input type="submit" value="Confirm">
    </form>

core/templates/todo/task_list.html
{% extends "base.html"%}
{% load humanize %}

{% block content %}
<form method="post" action="{% url 'todo:task-create' %}">
  {% csrf_token %}

  <input type="text" name="title" class="form-control form-control-lg" id="exampleFormControlInput1"
    placeholder="Add new..." required>
  <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>

</div>
</div>
</div>
</div>

<hr class="my-4">
{% if tasks %}
{% for task in tasks %}
<ul class="list-group list-group-horizontal rounded-0 bg-transparent">
  <li class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
    <div class="form-check">
      <p class="small mb-0">{{ task.created_date|naturaltime }}</p>
    </div>
  </li>
  <li class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
    {% if task.done == True %}
    <strike class="lead fw-normal mb-0">{{ task.title }}</strike>
    {% else %}
    <p class="lead fw-normal mb-0">{{ task.title }}</p>
    {% endif %}
  </li>
  <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
    <div class="d-flex flex-row justify-content-end mb-1 icon-align">
      {% if task.done == False %}
      <a href="{% url 'todo:task-edit' pk=task.id %}" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i
          class="fa fa-fw fa-edit me-3"></i></a>
      <a href="{% url 'todo:task-delete' pk=task.id %}" class="text-danger" data-mdb-toggle="tooltip"
        title="Delete todo"><i class="fa fa-fw fa-trash" aria-hidden="true"></i></a>
      <a href="{% url 'todo:task-done' pk=task.id %}" class="text-danger" data-mdb-toggle="tooltip" title="Done todo"><i
          class="fa fa-check" aria-hidden="true"></i></a>
      {% else %}
      <a href="{% url 'todo:task-delete' pk=task.id %}" class="text-danger" data-mdb-toggle="tooltip"
        title="Delete todo"><i class="fa fa-fw fa-trash" aria-hidden="true"></i></a>
      {% endif %}
    </div>
  </li>
</ul>
{% endfor %}
{% else %}<p class="lead fw-normal mb-0 no-task">You have no pending task!</p>{% endif %}
</div>
</div>
</div>
</div>
</div>
</section>
{% endblock %}